on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Java version
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Check
        run: ./gradlew check

      - name: Build applet
        run: ./gradlew buildJavaCard
